### ISSUE TITLE
Failed to run in python 3.6.8

### ISSUE THREAD

**Issue by T-2** [ArmisSecurity/urgent11-detector#3]
Error message:
python3 urgent11-detector.py 192.168.1.11 80

WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
[~] Running against 192.168.1.11:80
Traceback (most recent call last):
  File "urgent11-detector.py", line 55, in iptables_block_port
    iptc.easy.insert_rule('filter', 'INPUT', iptables_rule)
AttributeError: module 'iptc' has no attribute 'easy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urgent11-detector.py", line 304, in <module>
    main()
  File "urgent11-detector.py", line 300, in main
    run_detections(args.host, args.port)
  File "urgent11-detector.py", line 266, in run_detections
    detection.detect(port)
  File "urgent11-detector.py", line 138, in detect
    with get_safe_src_port() as src_port:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "urgent11-detector.py", line 76, in get_safe_src_port
    with bind_random_port() as port, iptables_block_port(port):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "urgent11-detector.py", line 58, in iptables_block_port
    iptc.easy.delete_rule('filter', 'INPUT', iptables_rule)
AttributeError: module 'iptc' has no attribute 'easy'

Any ideas?

**Comment by dor-zusman** [comment]
Hey!
Please make sure you are using the latest version of the **python-iptables** package.
Try running:
`pip install --upgrade python-iptables`

Regards,
Dor.

**Comment by T-2** [comment]
Dor thanks for the suggestion but now I have another problem

pip3 install --upgrade python-iptables

Collecting python-iptables
  Downloading https://files.pythonhosted.org/packages/08/5e/16a5ca35c420b8059eeb72716e316eeb6f0e59ce028998d36b2dc87554e5/python-iptables-0.14.0.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 1.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-byyurn7f/python-iptables/

Sorry I am a python noob. Any ideas on this one?

ti

**Comment by dor-zusman** [comment]
Hey again!
Try running `sudo apt-get install python3-setuptools`, and then run `pip install --upgrade python-iptables`.

Try googling some of the exceptions, the solution might be the first link :)

Good luck,
Dor

**Comment by T-2** [comment]
Dor:

Thanks I tried that and got yet another error. I will uninstall all I installed this morning and start over. There seems to be a problem with pip vs pip3. Maybe I will try the python 2 version.

Thanks for the help.

By the way I am running the full up to date version of python that comes with Linux mint 19.2 MATE. Surprised you have not had this problem reported to you before this.

**Comment by T-2** [comment]
Got it to work. There is some conflict with the OS's version when you try to upgrade python-iptables. If you use ~/.local/bin/pip3 install --upgrade --user python-iptables it does install the latest version. Then you have to update your path export PATH="$HOME/.local/bin:$PATH"
Then to run your program: sudo /home/user/.local/bin/urgent11-detector 192.168.1.1 80

Not quite as easy as your display on your main page would have you believe.

**Comment by dor-zusman** [comment]
Hey T-2,
All of your problems are generic package installation problems that relates to your python environment, not our code.
for more information on the subject, visit: 
https://packaging.python.org/tutorials/installing-packages/

Happy you got it to work!
Dor.
